### ISSUE TITLE
No issue just a thanks!

### ISSUE THREAD

**Issue by joakimbeng** [blakeembrey/node-immigration#25]
Hi,

I'm the author of [klei-migrate](https://github.com/klei/migrate) and have been needing support for storage adaptors for it in quite some time but haven't found the time to build it.
On my hunt for another migration tool with such support I found this module and it perfectly suits my needs! :) What makes the switch really easy is the fact that both `immigration` and `klei-migrate` uses the same module format for migration files and `klei-migrate`'s files are correctly recognized and run by `immigration`.

So I just want to say thanks!

PS. I will probably build an sql adaptor for immigration really soon so I'll update #23 if I'm the first :)

**Comment by blakeembrey** [comment]
Thanks! 😄 I'd be happy to help migrate some of the advanced features you built out into `immigration` too. Hopefully through `fs` and `rethinkdb` there's enough to go on for building your own adapter. I think building the SQL adapter should be pretty straightforward with something like `knex.js` (e.g. can support PG, MySQL, SQLite in one), I just never got around to it myself because I'm not using SQL. As for CoffeeScript support, I think it's a pretty simple thing to build into the CLI (currently I'd do `node -r coffeescript/register node_modules/immigration/dist/bin up --all`, but didn't test that) using `-r`/`--require` to register hooks.
